### ISSUE TITLE
Refactors

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/catalog#6]
- [ ] Change all the volumes in meta.yml to bases
- [ ] Shorten volume uuid to first 4 character
- [ ] use shorten volume id for base_name
- [ ] keep original base order in `order` attr. of base in meta.yml
- [ ] add base_file of each base in meta.yml

example:
------------------
```
  id: P000325
  initial_creation_type: ocr
  created_at: 12/03/2020
  last_modified_at: 2021-12-16 15:34:06.604704
  source: https://library.bdrc.io
  source_metadata:
    id: bdr:W1PD90121
    title: མའོ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
    author: ''
    bases:
      f3c9:
        image_group_id: I1PD90137
        title: Volume 1 of mao wen qiang zu zi zhi xian di ming lu
        total_pages: 220
        order: 1
        base_file: f3c9.txt
    access: http://purl.bdrc.io/admindata/AccessOpen
    restrictedInChina: false
```
